trigger:
  branches:
    include:
      - develop

pr:
  branches:
    include:
      - develop

resources:
  - repo: self

parameters:
  - name: environment
    displayName: Environment
    type: string
    default: DEV
    values:
      - DEV

  - name: applyTerraform
    displayName: Apply terraform?
    type: boolean
    default: false

  - name: destroyTerraform
    displayName: Run terraform DESTROY!!?
    type: boolean
    default: false

variables:
  azureServiceConnection: 'f4fc9f16-1394-4eb5-8bfc-9d4f7a26c06b'

  terraformDirectory: '$(Build.SourcesDirectory)/terraform'

  acrName: 'avantibootcampdevacr'
  containerRegistry: 'avantibootcampdevacr.azurecr.io'
  imageRepository: 'aivantibootcampimg'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  resourceGroupName: 'avanti-bootcamp-dev-rg'
  aksClusterName: 'avanti-bootcamp-dev-aks'

  imagePullSecret: 'avanti-acr-auth'
  vmImageName: 'ubuntu-latest'

stages:
  - stage: Terraform
    displayName: Terraform Plan Apply Destroy
    jobs:
      - job: TerraformJob
        displayName: Terraform Job
        pool:
          vmImage: windows-latest

        steps:
          - checkout: self
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          - task: AzureCLI@2
            displayName: Run Terraform Script
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              scriptType: ps
              scriptLocation: inlineScript
              workingDirectory: '$(terraformDirectory)'
              inlineScript: |
                Write-Host "Environment: ${{ parameters.environment }}"

                if ("${{ parameters.applyTerraform }}" -eq "True" -and "${{ parameters.destroyTerraform }}" -eq "True") {
                  throw "You cannot apply and destroy at the same time."
                }

                if ("${{ parameters.destroyTerraform }}" -eq "True") {
                  .\prepare_template1.ps1 ${{ parameters.environment }} -Destroy
                }
                elseif ("${{ parameters.applyTerraform }}" -eq "True") {
                  .\prepare_template1.ps1 ${{ parameters.environment }} -Apply
                }
                else {
                  .\prepare_template1.ps1 ${{ parameters.environment }}
                }
            env:
              TF_VAR_sql_admin_username: $(sqlAdminUsername)
              TF_VAR_sql_admin_password: $(sqlAdminPassword)

          - task: PublishBuildArtifacts@1
            displayName: Publish Terraform Plan Files
            condition: always()
            inputs:
              PathtoPublish: '$(Build.SourcesDirectory)/terraform/modules/template1'
              ArtifactName: 'terraform-plan-${{ parameters.environment }}'
              publishLocation: Container