kind: Service
apiVersion: v1
metadata:
  name: containerapp-todoapi-svc
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: containerapp-todoapi
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: containerapp-todoapi-deploy
  namespace: bootcamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: containerapp-todoapi
      tier: backend
  template:
    metadata:
      labels:
        app: containerapp-todoapi
        tier: backend
    spec:
      containers:
        - name: containerapp-todoapi
          image: avantibootcampacr.azurecr.io/containerapp-todoapi:latest
          env:
            - name: MyDbContext
              value: "Server=tcp:avanti-bootcamp-sql.database.windows.net,1433;Initial Catalog=bootcampdb;Persist Security Info=False;User ID=sqladminuser;Password=Ryanpassword123!;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
          # env:
          #   - name: ConnectionStrings__DefaultConnection
          #     valueFrom:
          #       secretKeyRef:
          #         name: sql-connection-secret
          #         key: SQL_CONNECTION_STRING
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: containerapp-todoapi-scaler
  namespace: bootcamp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: containerapp-todoapi-deploy
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 20